import { Metadata } from "next";
import "../app/global.css";

export const metadata: Metadata = {
  title: {
      absolute: "Next.js", // 
      default: "Next.js App", // makes this a default for all sub-sequent segments
      template: "%s | Next.js App" // applies to child segments
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "#171616",
            padding: "1rem",
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "#171616",
            padding: "1rem"
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
